"""add_content_items

Revision ID: ac82287cb8a3
Revises: 
Create Date: 2026-06-08 11:17:56.321058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac82287cb8a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('type', sa.Enum('vocab', 'grammar', 'pronunciation', 'reading', 'conversation', name='contenttype'), nullable=False),
    sa.Column('cefr', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('seed', 'ai', name='contentsource'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_items')
    # ### end Alembic commands ###
